version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.41
    - 15.0.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: eslint
    versions:
    - 7.24.0
